---

- name: Create ~vagrant/.ssh directory
  file: path=/home/vagrant/.ssh state=directory mode=0700 owner=vagrant

- name: Copy SSH private key
  copy: src=id_rsa dest=/home/vagrant/.ssh/id_rsa mode=0600 owner=vagrant

- name: Copy SSH public key
  copy: src=id_rsa.pub dest=/home/vagrant/.ssh/id_rsa.pub mode=0644 owner=vagrant

- name: Copy SSH known_hosts
  copy: src=known_hosts dest=/home/vagrant/.ssh/known_hosts mode=0644 owner=vagrant

- name: Copy SSH tunnel service
  copy: src=sshtunnel.upstart.conf dest=/etc/init/sshtunnel.conf

- name: Reload Upstart configuration
  command: initctl reload-configuration

- name: Start SSH tunnel service
  service: name=sshtunnel state=started

- name: Install apt-cacher-ng apt configuration
  copy: src=99apt-cacher-ng dest=/etc/apt/apt.conf.d/99apt-cacher-ng

- name: Install required packages
  apt: pkg={{item}} state=installed update_cache=yes
  with_items:
    - git
    - wget
    - ntp
    - sudo
    - procps

- name: Stop puppet service
  service: name=puppet state=stopped

- name: Stop chef-client service
  service: name=chef-client state=stopped

- name: Copy Oracle JDK
  copy: src=jdk-7u71-linux-x64.tar.gz dest=/home/vagrant/jdk-7u71-linux-x64.tar.gz

- name: Copy Oracle JDK installation script
  copy: src=install-oracle-jdk.sh dest=/home/vagrant/install-oracle-jdk.sh

- name: Run Oracle JDK installation script
  command: chdir=/home/vagrant bash install-oracle-jdk.sh


