---

- name: Ensure hadoop group exists
  group: name=hadoop state=present

- name: Set up user accounts for hadoop users
  user: name={{ item }} groups=hadoop state=present
  with_lines: cat ../../../hadoop-users.txt

