---

- hosts: slaves

  sudo: yes

  roles:
    - common
    - datanode
    - nodemanager

  vars:
    - hadoop_version: 2.7.3
 
- hosts: namenode

  sudo: yes

  roles:
    - common
    - namenode

  vars:
    - hadoop_version: 2.7.3

- hosts: resourcemanager

  sudo: yes

  roles:
    - common
    - resourcemanager

  vars:
    - hadoop_version: 2.7.3

- hosts: mrjobhistory

  sudo: yes

  roles:
    - common
    - mrjobhistory

  vars:
    - hadoop_version: 2.7.3

